platform :ios, '13.0'

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end

target 'Plugin' do
  capacitor_pods
  pod 'Firebase', '10.17.0'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'AWSMobileClient'
  pod 'AWSUserPoolsSignIn'
  pod 'AWSS3'
  pod 'AWSCore'
  pod 'Amplify', '1.30.4'
end

target 'PluginTests' do
  capacitor_pods
end
